version: '3.8'

services:
  db:
    image: postgres:13
    container_name: mm_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mm_network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: mm_backend
    command: uvicorn core.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    networks:
      - mm_network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: mm_frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    networks:
      - mm_network

networks:
  mm_network:
    driver: bridge

volumes:
  postgres_data:
